### ISSUE TITLE
plugin: Alexa4P3 some item attributes not defined

### ISSUE THREAD

**Issue by CannonRS** [smarthomeNG/plugins#592]
I'm getting the warning "Attribute is undefined" from "lib.metadata" because the item attributes alexa_alias, alexa_range_delta and alexa_color_temp_delta are not defined in plugin.yaml.

**Comment by msinn** [comment]
``alexa_alias`` is commented out in the metadata and has the description 'only for Payload V2 needed'.

I can't find any hint, that the attributes ``alexa_range_delta`` and ``alexa_color_temp_delta`` are implemented at all. So there is no need to define them in the metadata.

**Comment by Tom-Bom-badil** [comment]
I am getting similar errors for some of my self-made plugins when shNG is firing up. Since years, those plugins have device-specific attributes defined in the corresponding items.yaml (one example are the 'e0'..'e10' definitions [here](https://github.com/smarthomeNG/plugins/blob/e9f4b86983b08e1d81c37d13dadc52538d92cbd0/helios/files/helios.yaml#L291), which are producing 11 lines of error messages on every startup).

I learned from a discussion with the developers that this behavior is on purpose due to planned, yet not implemented shNG features, and that the errors would disappear in the newer shNG versions (which i don't run, also on purpose) after renaming the attributes at all possible appearances to **_my__**original_attribute_name.

As everything else is working fine, and the error is not an error, I decided to simply ignore this and to live with the ~30 error lines during shNG startup. I recommended the same to the several plugin users who contacted me why these errors appeared in their log files suddenly out of a nowhere.

/tom

**Comment by msinn** [comment]
> I'm still using the alexa_alias. It's working for me.
> 
> The alexa_alias I can see it working in the Web Interface, but it isn't in the documentation anymore. The alexa_range_delta is neccessary for shutters (see here: https://github.com/Andrek01/Alexa4PayloadV3). The alexa_color_temp_delta is not longer in the documentation, but it's using in **init**.py.

@Andrek01 Could you look into it?

**Comment by Andrek01** [comment]
I will take care about that, but it will take some time. The next two weekends are completly booked, so it will last till end of the month.

best regards
Andre

**Comment by msinn** [comment]
No problem, I just mentioned you, because I thought you were not aware of this issue in the plugins repository.

Now, since you accepted the invitation, I can assign new issues to you, if they are in relation to your plugins. :smile:

**Comment by Morg42** [comment]
Has anything happened here? Is this still an issue?

concerning the statement from Tom-Bom-Badil: if you insist on using an old core version (which is basically fine with me), you will have to accept that new plugin versions using new features will not run properly.
Do you have concise reasons to stay on old core versions? (Would you be willing to elaborate?)

**Comment by Tom-Bom-badil** [comment]
How did you come to the conclusion that I am using an 'old core version' (or did when I made my above comment 2.5 years ago)? Also, the comment is about one of the Plugins I programmed and maintained myself.

Did you even get what this discussion was about? We were *NOT* talking about new plugin features - instead, about core functionality that was available and used to work properly in the past, and that silently and suddenly 'disappeared'.

Anyways, I am in the process of migrating away from shNG, so feel free to disregard my comment, as it is obsolete.

/tom

**Comment by Andrek01** [comment]
Going back to the first issue, i checked the plugin.yaml. Cannon already added the missing attributes, i added the descriptions.
PR is initiated to develop-branch.
So everything should be fine now and the issue can be closed

best regards
Andre

P.S.: thanks to remind me

**Comment by Morg42** [comment]
solved by #984
